### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by ggg5269** [NDelventhal/cot_reports#4]
error occur in pip install  
`UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 5497: illegal multibyte sequence`  
see screenshot below  
  
![image](https://user-images.githubusercontent.com/37011770/150068682-1b37fe08-e904-4cba-8085-e637ee2ec22a.png)

**Comment by NDelventhal** [comment]
Much appreciated! Thanks for noticing me on this. I'll try to deploy a fix for this soon. The following should do the trick 

`long_description=open('README.md', 'r', encoding='utf-8').read() ` in the _setup.py_ file.

 I could imagine that a quick work-around for you could be to set your system locale to UTF-8. Or if you use Docker, where the locale may not be set up by default, set it accordingly to "UTF-8". That at least appears to be a common reason such an error comes up when trying to install pip modules.

**Comment by ggg5269** [comment]
Thanks for answering, what I do was just simply download the folder and
place beside my project.

Another suggestion, you could use package tempfile to temporarily place the
txt, but not leaving them everywhere. 🤔

Niall Delventhal ***@***.***> 於 2022年1月19日 週三 22:20 寫道：

**Comment by NDelventhal** [comment]
Thanks. Should work now. If not please let me know.
