### ISSUE TITLE
A New-Zealand dollar data  

### ISSUE THREAD

**Issue by gamaiun** [NDelventhal/cot_reports#7]
I have noticed that there seems to be an issue with the new_zealand ticker in the library. Specifically, the last year of data for this ticker appears to be from 2022, rather than the expected year of 2023. Any ideas?

**Comment by NDelventhal** [comment]
Hi @gamaiun,

no, there is no issue with the data. 

Starting with the 2022-02-08 report the market name at the CME name was changed to **NZ DOLLAR - CHICAGO MERCANTILE EXCHANGE** before it was **NEW ZEALAND DOLLAR - CHICAGO MERCANTILE EXCHANGE**. Looks like you solely filtered based on the outdated name. 

Run 

```
kiwi_df = df[df["Market and Exchange Names"].apply(lambda x: "NEW ZEALAND DOLLAR" in x or "NZ" in x)]

kiwi_df[["Market and Exchange Names", "As of Date in Form YYYY-MM-DD"]].groupby("Market and Exchange Names").agg({'As of Date in Form YYYY-MM-DD' : [min, max]})
```
for the following overview of past and active Kiwi Dollar markets:



![Kiwi Dollar](https://github.com/NDelventhal/cot_reports/assets/56277004/414fac38-2ad3-4813-8b8b-5bb99dc2beb9)
