### ISSUE TITLE
Error Append

### ISSUE THREAD

**Issue by dermatzeimnetz** [NDelventhal/cot_reports#9]
Newer Pandas Version do not have the "append" function

    df = cot.cot_all(cot_report_type='legacy_fut')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxxxx/.local/lib/python3.11/site-packages/cot_reports/cot_reports.py", line 190, in cot_all
    df = df.append(years, ignore_index=True)
         ^^^^^^^^^
  File "xxxxxx/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

**Comment by NDelventhal** [comment]
Vielen Dank @dermatzeimnetz for pointing out the issue & thanks to you @pfontana77 for offering a quick solution. A replacement of the deprecated pandas frame.append method has occurred in today's release. Now the package does support newer Python versions.
